env:
  es6: true
  browser: true
  commonjs: true

extends: "htmlacademy/es6"
rules:
  indent: off
  object-curly-spacing: off
  arrow-parens: off

parserOptions:
  ecmaVersion: 2015
  sourceType: "module"
